name: test Workflow

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: init
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.NAME }}
           git config --global user.email ${{ secrets.MAIL }}
           git config --global credential.helper store
           echo "https://${{ secrets.NAME }}:${{ secrets.TOKEN }}@github.com" > ~/.git-credentials
       - name: cloning repo
         continue-on-error: true
         run: |
           git clone https://${{ secrets.NAME }}:${{ secrets.TOKEN }}@${{ secrets.REPO }} test
       - name: Running
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd test
           python3 bot.py
       - name: Loop workflow
         continue-on-error: true
         run: |
              git clone https://github.com/${GH_PATH} loop
              cd loop || exit 1
              echo $(date -u +%T%P) >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop on $(date -u +%D-%T%P)"
              git push -q https://${{ secrets.TOKEN }}@github.com/${GH_PATH} HEAD:main