name: Run on workflows
on:
    schedule:
      - cron: "0 */6 * * *"
    push:
      branches: [ beta ]
    workflow_dispatch:
    
env:
  API_ID: "${{ secrets.API_ID }}"
  API_HASH: "${{ secrets.API_HASH }}"
  SESSION: "${{ secrets.SESSION }}"
  BOT_TOKEN: "${{ secrets.BOT_TOKEN }}"
  SESSION: "${{ secrets.SESSION }}"
  DB_URL: "${{ secrets.DB_URL }}"
  NSFW_API: "${{ secrets.NSFW_API }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  LOG_ID ="${{ secrets.LOG_ID }}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
         with:
            ref: beta
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancelling duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - uses: actions/setup-node@v2
         with:
            node-version: '16'
       - name: Set up Python 3.9
         uses: actions/setup-python@v2.2.2
         with:
           python-version: 3.9
       - name: cloning repo and install

         continue-on-error: true
         run: |
           sudo apt -qq update && sudo apt -qq install -y --no-install-recommends ffmpeg neofetch
           echo "https://${{ secrets.USERNAME }}:${{ secrets.TOKEN }}@github.com" > ~/.git-credentials
           git clone ${{ secrets.REPO_URL }} test && cd test && pip3 install -r requirements.txt
          #  echo "API_ID=${{ secrets.API_ID }} | tee .env
          #  echo "API_HASH=${{ secrets.API_HASH }} | tee -a .env
          #  echo "SESSION=${{ secrets.SESSION }} | tee -a .env
          #  echo "SUDO=${{ secrets.SUDO }} | tee -a .env
          #  echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }} | tee -a .env || echo "Proceeding with no bot"
          #  cat .env
       - name: Running
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd test && python3 -m Main