name: Run on workflows
on:
    schedule:
      - cron: "0 */6 * * *"
    push:
      branches: [ ub ]
    workflow_dispatch:
    
env:
  API_ID: "${{ secrets.API_ID }}"
  API_HASH: "${{ secrets.API_HASH }}"
  SESSION: "${{ secrets.SESSION }}"
  BOT_TOKEN: "${{ secrets.BOT_TOKEN }}"
  DB_URL: "${{ secrets.DB_URL }}"
  NSFW_API: "${{ secrets.NSFW_API }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  LOG_ID: "${{ secrets.LOG_ID }}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
         with:
            ref: ub
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancelling duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - uses: actions/setup-node@v2
         with:
            node-version: '16'
       - name: Set up Python 3.9
         uses: actions/setup-python@v2.2.2
         with:
           python-version: 3.9
       - name: cloning repo and install

         continue-on-error: true
         run: |
           apt -qq update && apt -qq install -y --no-install-recommends git ffmpeg neofetch
           git clone https://${{ secrets.TOKEN }}@github.com/${{ secrets.PATH }} test && cd test && pip3 install -r requirements.txt
       - name: Running
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd test && python3 -m Main
