name: PythonAutoLint
on:
  push:
    paths:
    - "**.py"
  workflow_dispatch:
jobs:
  pyLint:
    runs-on: ubuntu-latest
    steps:
      - name: Init
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install mandatory dependencies
        run: pip install autopep8 autoflake isort black
      - name: "[autopep8] Format fix"
        run: |
          find -name "*.py" -not -path "./venv/*" -exec autopep8 --verbose --in-place --recursive --aggressive --aggressive '{}' \;
      - name: "[autoflake] Remove unused imports and variables"
        run: |
          find . -regex "^.\/\Main\/\w+\/.+\.py$" -exec autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports -v -v '{}' \;
      - name: "[black] lint"
        run: |
          black -v .
      - name: "[isort] lint"
        run: |
          isort -v --cs --ca --ls --lss --ds --fss --lai 2 -m 4 .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: .
          commit_user_name: wrench
          commit_options: '--no-verify'
          commit_user_email: me@jyothis.gq
          commit_message: 'auto: format / refactor'
          commit_author: EverythingSuckz <me@jyothis.gq>
